# Generated by Django 5.0 on 2023-12-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='receipt',
            field=models.CharField(default='receipts', max_length=100),
        ),
    ]
