# Generated by Django 5.0 on 2023-12-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_checkout_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesabody',
            options={'ordering': ['-created_at']},
        ),
    ]
