# Generated by Django 5.0 on 2023-12-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_mpesabody_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-created_at']},
        ),
    ]
